[package]
name = "hiccup"
version = "0.1.1"
authors = ["Julia Naomi <jnboeira@outlook.com>"]
description = "Rust HTML macro inspired by Clojure's Hiccup"
repository = "https://github.com/naomijub/edn-rs"
keywords = ["HTML", "Hiccup"]
license = "GPL-3.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
